### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Alvin-LH** [chenmingxiang110/Chinese-automatic-speech-recognition#11]
你好，打扰你了当我换一个语音文件的时候，就会报错：
Traceback (most recent call last):
  File "C:/Users/lihao/Desktop/Chinese-automatic-speech-recognition-master/test.py", line 46, in <module>
    data = zero_padding_1d(data, 160240)
  File "C:\Users\lihao\Desktop\Chinese-automatic-speech-recognition-master\lib\tools_math.py", line 46, in zero_padding_1d
    result = np.concatenate([vec, np.zeros(obj_length-len(vec))])
ValueError: negative dimensions are not allowed

是因为语音的采样率有限制吗，如果是这样，有什么好的解决办法吗，谢谢不胜感激

**Comment by chenmingxiang110** [comment]
你好，我这做了最长音频的长度限制（大约10秒），你这个可能是超过最长的长度了

Mingxiang Chen

730 Escondido Rd,

Stanford, California 94305
650-441-8408


Alvin-LH ***@***.***> 于2021年9月1日周三 下午9:56写道：
